<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $role = Role::where('name', 'student')->first();
        if (!$role) {
            $role = Role::create(['name' => 'student', 'guard_name' => 'web']);
        }

        $students = [
            [
                'name' => 'Ahmad Pratama',
                'gender' => 'L',
                'address' => 'Jl. Mawar No. 10, Jakarta',
                'contact' => '081234567001',
                'email' => '20388@student.stembayo.sch.id',
                'nis' => '20388',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Siti Nurhaliza',
                'gender' => 'P',
                'address' => 'Jl. Melati No. 15, Jakarta',
                'contact' => '081234567002',
                'email' => '20389@student.stembayo.sch.id',
                'nis' => '20389',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Budi Santoso',
                'gender' => 'L',
                'address' => 'Jl. Kenanga No. 20, Jakarta',
                'contact' => '081234567003',
                'email' => '20390@student.stembayo.sch.id',
                'nis' => '20390',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Dewi Sartika',
                'gender' => 'P',
                'address' => 'Jl. Anggrek No. 25, Jakarta',
                'contact' => '081234567004',
                'email' => '20391@student.stembayo.sch.id',
                'nis' => '20391',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Rizki Ramadhan',
                'gender' => 'L',
                'address' => 'Jl. Dahlia No. 30, Jakarta',
                'contact' => '081234567005',
                'email' => '20392@student.stembayo.sch.id',
                'nis' => '20392',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Maya Sari',
                'gender' => 'P',
                'address' => 'Jl. Tulip No. 35, Jakarta',
                'contact' => '081234567006',
                'email' => '20393@student.stembayo.sch.id',
                'nis' => '20393',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Andi Wijaya',
                'gender' => 'L',
                'address' => 'Jl. Kamboja No. 40, Jakarta',
                'contact' => '081234567007',
                'email' => '20394@student.stembayo.sch.id',
                'nis' => '20394',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Lestari Indah',
                'gender' => 'P',
                'address' => 'Jl. Sakura No. 45, Jakarta',
                'contact' => '081234567008',
                'email' => '20395@student.stembayo.sch.id',
                'nis' => '20395',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Fajar Nugroho',
                'gender' => 'L',
                'address' => 'Jl. Flamboyan No. 50, Jakarta',
                'contact' => '081234567009',
                'email' => '20396@student.stembayo.sch.id',
                'nis' => '20396',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Rina Kartika',
                'gender' => 'P',
                'address' => 'Jl. Bougenvil No. 55, Jakarta',
                'contact' => '081234567010',
                'email' => '20397@student.stembayo.sch.id',
                'nis' => '20397',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Dimas Prakoso',
                'gender' => 'L',
                'address' => 'Jl. Cempaka No. 60, Jakarta',
                'contact' => '081234567011',
                'email' => '20398@student.stembayo.sch.id',
                'nis' => '20398',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Ayu Permatasari',
                'gender' => 'P',
                'address' => 'Jl. Gardenia No. 65, Jakarta',
                'contact' => '081234567012',
                'email' => '20399@student.stembayo.sch.id',
                'nis' => '20399',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Hendra Setiawan',
                'gender' => 'L',
                'address' => 'Jl. Lavender No. 70, Jakarta',
                'contact' => '081234567013',
                'email' => '20400@student.stembayo.sch.id',
                'nis' => '20400',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Putri Maharani',
                'gender' => 'P',
                'address' => 'Jl. Peony No. 75, Jakarta',
                'contact' => '081234567014',
                'email' => '20401@student.stembayo.sch.id',
                'nis' => '20401',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Agus Susanto',
                'gender' => 'L',
                'address' => 'Jl. Iris No. 80, Jakarta',
                'contact' => '081234567015',
                'email' => '20402@student.stembayo.sch.id',
                'nis' => '20402',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Sari Rahayu',
                'gender' => 'P',
                'address' => 'Jl. Azalea No. 85, Jakarta',
                'contact' => '081234567016',
                'email' => '20403@student.stembayo.sch.id',
                'nis' => '20403',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Bayu Aditya',
                'gender' => 'L',
                'address' => 'Jl. Begonia No. 90, Jakarta',
                'contact' => '081234567017',
                'email' => '20404@student.stembayo.sch.id',
                'nis' => '20404',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Eka Fitriani',
                'gender' => 'P',
                'address' => 'Jl. Camellia No. 95, Jakarta',
                'contact' => '081234567018',
                'email' => '20405@student.stembayo.sch.id',
                'nis' => '20405',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Doni Hermawan',
                'gender' => 'L',
                'address' => 'Jl. Daffodil No. 100, Jakarta',
                'contact' => '081234567019',
                'email' => '20406@student.stembayo.sch.id',
                'nis' => '20406',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Fitri Handayani',
                'gender' => 'P',
                'address' => 'Jl. Edelweiss No. 105, Jakarta',
                'contact' => '081234567020',
                'email' => '20407@student.stembayo.sch.id',
                'nis' => '20407',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Galih Prasetyo',
                'gender' => 'L',
                'address' => 'Jl. Freesia No. 110, Jakarta',
                'contact' => '081234567021',
                'email' => '20408@student.stembayo.sch.id',
                'nis' => '20408',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Hani Rahmawati',
                'gender' => 'P',
                'address' => 'Jl. Geranium No. 115, Jakarta',
                'contact' => '081234567022',
                'email' => '20409@student.stembayo.sch.id',
                'nis' => '20409',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Irfan Hakim',
                'gender' => 'L',
                'address' => 'Jl. Hibiscus No. 120, Jakarta',
                'contact' => '081234567023',
                'email' => '20410@student.stembayo.sch.id',
                'nis' => '20410',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Jasmine Putri',
                'gender' => 'P',
                'address' => 'Jl. Impatiens No. 125, Jakarta',
                'contact' => '081234567024',
                'email' => '20411@student.stembayo.sch.id',
                'nis' => '20411',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Kevin Andika',
                'gender' => 'L',
                'address' => 'Jl. Jasmine No. 130, Jakarta',
                'contact' => '081234567025',
                'email' => '20412@student.stembayo.sch.id',
                'nis' => '20412',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Linda Suharto',
                'gender' => 'P',
                'address' => 'Jl. Kalanchoe No. 135, Jakarta',
                'contact' => '081234567026',
                'email' => '20413@student.stembayo.sch.id',
                'nis' => '20413',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Muhammad Firdaus',
                'gender' => 'L',
                'address' => 'Jl. Lily No. 140, Jakarta',
                'contact' => '081234567027',
                'email' => '20414@student.stembayo.sch.id',
                'nis' => '20414',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Nur Azizah',
                'gender' => 'P',
                'address' => 'Jl. Magnolia No. 145, Jakarta',
                'contact' => '081234567028',
                'email' => '20415@student.stembayo.sch.id',
                'nis' => '20415',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Oscar Pratama',
                'gender' => 'L',
                'address' => 'Jl. Narcissus No. 150, Jakarta',
                'contact' => '081234567029',
                'email' => '20416@student.stembayo.sch.id',
                'nis' => '20416',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Prita Maharani',
                'gender' => 'P',
                'address' => 'Jl. Orchid No. 155, Jakarta',
                'contact' => '081234567030',
                'email' => '20417@student.stembayo.sch.id',
                'nis' => '20417',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Qori Hidayat',
                'gender' => 'L',
                'address' => 'Jl. Pansy No. 160, Jakarta',
                'contact' => '081234567031',
                'email' => '20418@student.stembayo.sch.id',
                'nis' => '20418',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Rani Septiani',
                'gender' => 'P',
                'address' => 'Jl. Poppy No. 165, Jakarta',
                'contact' => '081234567032',
                'email' => '20419@student.stembayo.sch.id',
                'nis' => '20419',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Satria Wibowo',
                'gender' => 'L',
                'address' => 'Jl. Petunia No. 170, Jakarta',
                'contact' => '081234567033',
                'email' => '20420@student.stembayo.sch.id',
                'nis' => '20420',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Tyas Ningrum',
                'gender' => 'P',
                'address' => 'Jl. Sunflower No. 175, Jakarta',
                'contact' => '081234567034',
                'email' => '20421@student.stembayo.sch.id',
                'nis' => '20421',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Usman Hakim',
                'gender' => 'L',
                'address' => 'Jl. Zinnia No. 180, Jakarta',
                'contact' => '081234567035',
                'email' => '20422@student.stembayo.sch.id',
                'nis' => '20422',
                'status_pkl' => 'Tidak Aktif',
            ],
            [
                'name' => 'Vina Amelia',
                'gender' => 'P',
                'address' => 'Jl. Violet No. 185, Jakarta',
                'contact' => '081234567036',
                'email' => '20423@student.stembayo.sch.id',
                'nis' => '20423',
                'status_pkl' => 'Tidak Aktif',
            ],
        ];

        foreach ($students as $studentData) {
            $student = Student::create($studentData);
            $student->assignRole($role);
        }
    }
}
